<?php
return [
    'questions' => [
        array( // row #0
            'id' => 1,
            'text' => 'Кто съел чужой обед?',
        ),
        array( // row #1
            'id' => 2,
            'text' => 'Вам говорят на уроке: «Немедленно прекратите!» Чем это вы занимаетесь?',
        ),
        array( // row #2
            'id' => 3,
            'text' => 'Чем рисует ребёнок?',
        ),
        array( // row #3
            'id' => 4,
            'text' => 'Почему плачет ребёнок?',
        ),
        array( // row #4
            'id' => 5,
            'text' => 'С чего начинается рабочий день?',
        ),
        array( // row #5
            'id' => 6,
            'text' => 'Обязательный атрибут красивой жизни',
        ),
        array( // row #6
            'id' => 7,
            'text' => 'Что должно быть чистым?',
        ),
        array( // row #7
            'id' => 8,
            'text' => 'Кто сидит на дереве?',
        ),
        array( // row #8
            'id' => 9,
            'text' => 'Почему ученик не выполнил домашнее задание?',
        ),
        array( // row #9
            'id' => 10,
            'text' => 'У кого лучше списывать контрольную работу?',
        ),
        array( // row #10
            'id' => 11,
            'text' => 'Что делать, если забыл сменную обувь?',
        ),
        array( // row #11
            'id' => 12,
            'text' => 'У кого из великих фамилия на букву М?',
        ),
        array( // row #12
            'id' => 13,
            'text' => 'Утром вы принимаете душ и громко ругаетесь. Почему?',
        ),
    ],

    "answers" => [
        array( // row #0
            'id' => 1,
            'question_id' => 1,
            'line' => 1,
            'text' => 'Сосед',
            'score' => 31,
        ),
        array( // row #1
            'id' => 2,
            'question_id' => 1,
            'line' => 2,
            'text' => 'Самый голодный',
            'score' => 25,
        ),
        array( // row #2
            'id' => 3,
            'question_id' => 1,
            'line' => 3,
            'text' => 'Одноклассник',
            'score' => 15,
        ),
        array( // row #3
            'id' => 4,
            'question_id' => 1,
            'line' => 4,
            'text' => 'Васька (Петька, Маша и т. п.)',
            'score' => 15,
        ),
        array( // row #4
            'id' => 5,
            'question_id' => 1,
            'line' => 5,
            'text' => 'Обжора',
            'score' => 8,
        ),
        array( // row #5
            'id' => 6,
            'question_id' => 1,
            'line' => 6,
            'text' => 'Самый толстый',
            'score' => 6,
        ),
        array( // row #6
            'id' => 7,
            'question_id' => 2,
            'line' => 1,
            'text' => 'Разговариваем',
            'score' => 39,
        ),
        array( // row #7
            'id' => 8,
            'question_id' => 2,
            'line' => 2,
            'text' => 'Слушаю музыку',
            'score' => 16,
        ),
        array( // row #8
            'id' => 9,
            'question_id' => 2,
            'line' => 3,
            'text' => 'Играю на телефоне',
            'score' => 13,
        ),
        array( // row #9
            'id' => 10,
            'question_id' => 2,
            'line' => 4,
            'text' => 'Смеюсь',
            'score' => 7,
        ),
        array( // row #10
            'id' => 11,
            'question_id' => 2,
            'line' => 5,
            'text' => 'Сплю',
            'score' => 6,
        ),
        array( // row #11
            'id' => 12,
            'question_id' => 2,
            'line' => 6,
            'text' => 'Списываю',
            'score' => 3,
        ),
        array( // row #12
            'id' => 13,
            'question_id' => 3,
            'line' => 1,
            'text' => 'Руками',
            'score' => 26,
        ),
        array( // row #13
            'id' => 14,
            'question_id' => 3,
            'line' => 2,
            'text' => 'Пальцем',
            'score' => 20,
        ),
        array( // row #14
            'id' => 15,
            'question_id' => 3,
            'line' => 3,
            'text' => 'Карандашом',
            'score' => 17,
        ),
        array( // row #15
            'id' => 16,
            'question_id' => 3,
            'line' => 4,
            'text' => 'Красками',
            'score' => 6,
        ),
        array( // row #16
            'id' => 17,
            'question_id' => 3,
            'line' => 5,
            'text' => 'Фломастером',
            'score' => 5,
        ),
        array( // row #17
            'id' => 18,
            'question_id' => 3,
            'line' => 6,
            'text' => 'Мелом',
            'score' => 5,
        ),
        array( // row #18
            'id' => 19,
            'question_id' => 4,
            'line' => 1,
            'text' => 'Хочет есть',
            'score' => 27,
        ),
        array( // row #19
            'id' => 20,
            'question_id' => 4,
            'line' => 2,
            'text' => 'Устал',
            'score' => 12,
        ),
        array( // row #20
            'id' => 21,
            'question_id' => 4,
            'line' => 3,
            'text' => 'Описался',
            'score' => 11,
        ),
        array( // row #21
            'id' => 22,
            'question_id' => 4,
            'line' => 4,
            'text' => 'Упал',
            'score' => 8,
        ),
        array( // row #22
            'id' => 23,
            'question_id' => 4,
            'line' => 5,
            'text' => 'Обидели',
            'score' => 4,
        ),
        array( // row #23
            'id' => 24,
            'question_id' => 4,
            'line' => 6,
            'text' => 'Зубки режутся',
            'score' => 3,
        ),
        array( // row #24
            'id' => 25,
            'question_id' => 5,
            'line' => 1,
            'text' => 'С кофе',
            'score' => 40,
        ),
        array( // row #25
            'id' => 26,
            'question_id' => 5,
            'line' => 2,
            'text' => 'С утра',
            'score' => 15,
        ),
        array( // row #26
            'id' => 27,
            'question_id' => 5,
            'line' => 3,
            'text' => 'С завтрака',
            'score' => 12,
        ),
        array( // row #27
            'id' => 28,
            'question_id' => 5,
            'line' => 4,
            'text' => 'С прихода на работу',
            'score' => 5,
        ),
        array( // row #28
            'id' => 29,
            'question_id' => 5,
            'line' => 5,
            'text' => 'С опоздания',
            'score' => 4,
        ),
        array( // row #29
            'id' => 30,
            'question_id' => 5,
            'line' => 6,
            'text' => 'С пробок',
            'score' => 2,
        ),
        array( // row #30
            'id' => 31,
            'question_id' => 6,
            'line' => 1,
            'text' => 'Деньги',
            'score' => 32,
        ),
        array( // row #31
            'id' => 32,
            'question_id' => 6,
            'line' => 2,
            'text' => 'Машина',
            'score' => 19,
        ),
        array( // row #32
            'id' => 33,
            'question_id' => 6,
            'line' => 3,
            'text' => 'Счастье',
            'score' => 16,
        ),
        array( // row #33
            'id' => 34,
            'question_id' => 6,
            'line' => 4,
            'text' => 'Любовь',
            'score' => 6,
        ),
        array( // row #34
            'id' => 35,
            'question_id' => 6,
            'line' => 5,
            'text' => 'Яхта',
            'score' => 5,
        ),
        array( // row #35
            'id' => 36,
            'question_id' => 6,
            'line' => 6,
            'text' => 'Квартира',
            'score' => 4,
        ),
        array( // row #36
            'id' => 37,
            'question_id' => 7,
            'line' => 1,
            'text' => 'Руки',
            'score' => 27,
        ),
        array( // row #37
            'id' => 38,
            'question_id' => 7,
            'line' => 2,
            'text' => 'Совесть',
            'score' => 16,
        ),
        array( // row #38
            'id' => 39,
            'question_id' => 7,
            'line' => 3,
            'text' => 'Одежда',
            'score' => 6,
        ),
        array( // row #39
            'id' => 40,
            'question_id' => 7,
            'line' => 4,
            'text' => 'Посуда',
            'score' => 5,
        ),
        array( // row #40
            'id' => 41,
            'question_id' => 7,
            'line' => 5,
            'text' => 'Зубы',
            'score' => 5,
        ),
        array( // row #41
            'id' => 42,
            'question_id' => 7,
            'line' => 6,
            'text' => 'Тело',
            'score' => 4,
        ),
        array( // row #42
            'id' => 43,
            'question_id' => 8,
            'line' => 1,
            'text' => 'Птица',
            'score' => 41,
        ),
        array( // row #43
            'id' => 44,
            'question_id' => 8,
            'line' => 2,
            'text' => 'Дятел',
            'score' => 26,
        ),
        array( // row #44
            'id' => 45,
            'question_id' => 8,
            'line' => 3,
            'text' => 'Кот',
            'score' => 26,
        ),
        array( // row #45
            'id' => 46,
            'question_id' => 8,
            'line' => 4,
            'text' => 'Ворона',
            'score' => 22,
        ),
        array( // row #46
            'id' => 47,
            'question_id' => 8,
            'line' => 5,
            'text' => 'Кошка',
            'score' => 17,
        ),
        array( // row #47
            'id' => 48,
            'question_id' => 8,
            'line' => 6,
            'text' => 'Белка',
            'score' => 13,
        ),
        array( // row #48
            'id' => 49,
            'question_id' => 9,
            'line' => 1,
            'text' => 'Не захотел ',
            'score' => 50,
        ),
        array( // row #49
            'id' => 50,
            'question_id' => 9,
            'line' => 2,
            'text' => 'Забыл',
            'score' => 25,
        ),
        array( // row #50
            'id' => 51,
            'question_id' => 9,
            'line' => 3,
            'text' => 'Гулял',
            'score' => 15,
        ),
        array( // row #51
            'id' => 52,
            'question_id' => 9,
            'line' => 4,
            'text' => 'Не смог',
            'score' => 4,
        ),
        array( // row #52
            'id' => 53,
            'question_id' => 9,
            'line' => 5,
            'text' => 'Спал',
            'score' => 4,
        ),
        array( // row #53
            'id' => 54,
            'question_id' => 9,
            'line' => 6,
            'text' => 'Он его никогда не делает',
            'score' => 2,
        ),
        array( // row #54
            'id' => 55,
            'question_id' => 10,
            'line' => 1,
            'text' => 'У отличника',
            'score' => 64,
        ),
        array( // row #55
            'id' => 56,
            'question_id' => 10,
            'line' => 2,
            'text' => 'У соседа',
            'score' => 29,
        ),
        array( // row #56
            'id' => 57,
            'question_id' => 10,
            'line' => 3,
            'text' => 'Со шпаргалки',
            'score' => 3,
        ),
        array( // row #57
            'id' => 58,
            'question_id' => 10,
            'line' => 4,
            'text' => 'У друга',
            'score' => 2,
        ),
        array( // row #58
            'id' => 59,
            'question_id' => 10,
            'line' => 5,
            'text' => 'У одноклассника',
            'score' => 1,
        ),
        array( // row #59
            'id' => 60,
            'question_id' => 10,
            'line' => 6,
            'text' => 'У учителя',
            'score' => 1,
        ),
        array( // row #60
            'id' => 61,
            'question_id' => 11,
            'line' => 1,
            'text' => 'Идти на урок без сменки',
            'score' => 46,
        ),
        array( // row #61
            'id' => 62,
            'question_id' => 11,
            'line' => 2,
            'text' => 'Пойти домой за сменкой',
            'score' => 20,
        ),
        array( // row #62
            'id' => 63,
            'question_id' => 11,
            'line' => 3,
            'text' => 'Помыть обувь',
            'score' => 17,
        ),
        array( // row #63
            'id' => 64,
            'question_id' => 11,
            'line' => 4,
            'text' => 'Уйти домой',
            'score' => 12,
        ),
        array( // row #64
            'id' => 65,
            'question_id' => 11,
            'line' => 5,
            'text' => 'Объяснить учителю ситуацию',
            'score' => 4,
        ),
        array( // row #65
            'id' => 66,
            'question_id' => 11,
            'line' => 6,
            'text' => 'Отобрать у другого',
            'score' => 1,
        ),
        array( // row #66
            'id' => 67,
            'question_id' => 12,
            'line' => 1,
            'text' => 'Менделеев',
            'score' => 37,
        ),
        array( // row #67
            'id' => 68,
            'question_id' => 12,
            'line' => 2,
            'text' => 'Моцарт',
            'score' => 12,
        ),
        array( // row #68
            'id' => 69,
            'question_id' => 12,
            'line' => 3,
            'text' => 'Медведев',
            'score' => 10,
        ),
        array( // row #69
            'id' => 70,
            'question_id' => 12,
            'line' => 4,
            'text' => 'Маяковский',
            'score' => 4,
        ),
        array( // row #70
            'id' => 71,
            'question_id' => 12,
            'line' => 5,
            'text' => 'Маркс',
            'score' => 3,
        ),
        array( // row #71
            'id' => 72,
            'question_id' => 12,
            'line' => 6,
            'text' => 'Муссолини',
            'score' => 3,
        ),
        array( // row #72
            'id' => 73,
            'question_id' => 13,
            'line' => 1,
            'text' => 'Нет горячей воды',
            'score' => 25,
        ),
        array( // row #73
            'id' => 74,
            'question_id' => 13,
            'line' => 2,
            'text' => 'Нет холодной воды',
            'score' => 24,
        ),
        array( // row #74
            'id' => 75,
            'question_id' => 13,
            'line' => 3,
            'text' => 'Мыло упало',
            'score' => 16,
        ),
        array( // row #75
            'id' => 76,
            'question_id' => 13,
            'line' => 4,
            'text' => 'Кто-то включил воду в другом месте',
            'score' => 15,
        ),
        array( // row #76
            'id' => 77,
            'question_id' => 13,
            'line' => 5,
            'text' => 'Мыло кончилось',
            'score' => 8,
        ),
        array( // row #77
            'id' => 78,
            'question_id' => 13,
            'line' => 6,
            'text' => 'Поскользнулся',
            'score' => 3,
        ),
    ]
];
